#!/bin/sh
# Gives a dmenu prompt to mount unmounted drives.
# If they're in /etc/fstab, they'll be mounted automatically.
# Otherwise, you'll be prompted to give a mountpoint from already existsing directories.
# If you input a novel directory, it will prompt you to create that directory.
pgrep -x dmenu && exit

getmount() { \
	[ -z "$chosen" ] && exit 1
	mp="$(find $1 2>/dev/null | dmenu -i -p "Type in mount point.")"
	[ "$mp" = "" ] && exit 1
	if [ ! -d "$mp" ]; then
		mkdiryn=$(printf "No\\nYes" | dmenu -i -p "$mp does not exist. Create it?")
		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
	fi
	}

mountusb() { \
	chosen="$(echo "$usbdrives" | dmenu -i -p "Mount which drive?" | awk '{print $1}')"
	sudo -A mount "$chosen" && exit 0
	getmount "/mnt /media /mount /home -type d -maxdepth 5"
	sudo -A mount "$chosen" "$mp" && pgrep -x dunst && notify-send "$chosen mounted to $mp."
	}

mountandroid() { \
	chosen=$(echo "$anddrives" | dmenu -i -p "Which Android device?" | cut -d : -f 1)
	getmount "$HOME -type d -maxdepth 3"
	simple-mtpfs --device "$chosen" "$mp"
	echo simple-mtpfs --device "$chosen" "$mp"
	}

mounthomeshare() { \
    homeshares="$(grep /hollywood /etc/fstab | awk '{ print $2 }' | awk -F/ '{ print $3 }')"
	chosen="$(echo "$homeshares" | dmenu -i -p "Mount which drive?" | awk '{print $1}')"
    source="$(grep $chosen /etc/fstab | awk '{ print $1 }')"
	getmount "/mnt -type d -maxdepth 1 -name $chosen"
	sudo -A mount "$source" "$mp" && pgrep -x dunst && notify-send "$chosen mounted to $mp."
	}

asktype() { \
	case $(printf "USB\\nAndroid\\nHomeShare" | dmenu -i -p "Mount a USB drive or Android device?") in
		USB) mountusb ;;
		Android) mountandroid ;;
		HomeShare) mounthomeshare ;;
	esac
	}

systemdrive=$(blkid | grep -i antiX | head -1 | sed 's/[0-9].*//')
anddrives=$(simple-mtpfs -l 2>/dev/null)
usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}' | grep -v $systemdrive)"

if [ -z "$usbdrives" ]; then
	#[ -z "$anddrives" ] && echo "No USB drive or Android device detected" && exit
	if [ -z "$anddrives" ]; then
        asktype
    else
	    echo "Android device detected."
	    mountandroid
    fi
else
	echo "USB drive(s) detected."
	[ -z "$anddrives" ] && echo "USB drive detected." && mountusb
	echo "Mountable USB drive(s) and Android device(s) detected."
	asktype
fi
