#!/bin/sh
# A dmenu prompt to unmount drives.
# Provides you with mounted partitions, select one to unmount.
# Drives mounted at /, /boot and /home will not be options to unmount.

unmountusb() {
	[ -z "$drives" ] && exit
	chosen=$(echo "$drives" | dmenu -i -p "Unmount which drive?" | awk '{print $1}')
	[ -z "$chosen" ] && exit
	sudo -A umount "$chosen" && pgrep -x dunst && notify-send "$chosen unmounted."
	}

unmountandroid() { \
	chosen=$(awk '/simple-mtpfs/ {print $2}' /etc/mtab | dmenu -i -p "Unmount which device?")
	[ -z "$chosen" ] && exit
	fusermount -u "$chosen" && pgrep -x dunst && notify-send "$chosen unmounted."
	}

unmounthomeshare() { \
    set -xv
	chosen="$(echo "$homeshares" | dmenu -i -p "Unmount which drive?" | awk '{print $1}')"
    source="$(grep $chosen /etc/fstab | awk '{ print $1 }')"
	sudo -A umount "$source"
    if [ $? -eq 0 ]; then
        pgrep -x dunst && notify-send "$chosen unmounted."
    else
        pgrep -x dunst && notify-send "$chosen is use by $(lsof +D $chosen | tail -1 | cut -d " " -f 1)."
    fi
	}

asktype() { \
	case $(printf "USB\\nAndroid\\nHomeShare" | dmenu -i -p "Unmount a USB drive or Android device?") in
		USB) unmountusb ;;
		Android) unmountandroid ;;
		HomeShare) unmounthomeshare ;;
	esac
	}

drives=$(lsblk -nrpo "name,type,size,mountpoint" | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}')
homeshares=$(mount | grep : | cut -d ' ' -f 3)

if ! grep simple-mtpfs /etc/mtab; then
	if [ -z "$drives" ]; then
        # echo "No USB drives to unmount."
        [ ! -z "$homeshares" ] && unmounthomeshare && exit
    else
	    echo "Unmountable USB drive detected."
	    unmountusb
    fi
else
	[ -z "$drives" ] && echo "Unmountable Android device detected." && unmountandroid
	echo "Unmountable USB drive(s) and Android device(s) detected."
	asktype
fi
