#!/bin/bash

# i3 startups for Virtualbox on Macbook Pro

case $HW in
    x230)
        echo "ThinkPad X230 i3 startups"
        compton &
        ;;
    mbp)
        echo "Macbook Pro i3 startups"
        # set internal monitor resolution
        xrandr --dpi 112 --output LVDS1
        xrdb -merge ~/Code/idf/.xresources-mbp-2012
        # Compsite manager
        compton &
        ;;
    x220|t520)
        echo "ThinkPad X220|T520 i3 startups"
        # Compsite manager
        compton &
        ;;
    general|*)
        echo "Default i3 startips"
        # Compsite manager
        compton &
        ;;
esac
