#!/bin/bash

# i3 screen brightness

case $HW in
    vbox-mbp)
        #echo "VirtualBox in Macbook Pro"
        ;;
    mbp)
        # set internal monitor resolution
        actual=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
        max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
        ;;
    x220|t520)
        # set internal monitor resolution
        # set internal monitor resolution
        actual=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
        max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
        ;;
    general|*)
        #echo "VirtualBox in Macbook Pro"
        ;;
esac

NUM=$(($actual * 100 / $max))

if [ "$NUM" -ge 80 ]; then
	color="#FFAE00"
elif [ "$NUM" -ge 60 ]; then
	color="#FFF600"
elif [ "$NUM" -ge 40 ]; then
	color="#FFFFFF"
elif [ "$NUM" -ge 20 ]; then
	color="#00FF00"
else
	color="#FF0000"
fi


echo "<span color='$color'>🌅$NUM%</span>"
