#!/bin/sh

# Feed script a url.
# If an image, it will view in feh,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

# Sci-Hub's domain occasionally changes due to shutdowns:
scihub="http://sci-hub.tw/"

# If no url given. Opens browser. For using script as $BROWSER.
#[ -z "$1" ] && { "$TRUEBROWSER"; exit; }

url="$1"

# If no url given, get link from clipboard
[ -z "$1" ] && url="$(xclip -o -selection clipboar)"

case "$url" in
	*mkv|*webm|*mp4|*gif|*hooktube.com*)
		setsid mpv -quiet "$url" >/dev/null 2>&1 & ;;
	*youtube.com*)
		setsid proxychains mpv -quiet "$url" >/dev/null 2>&1 & ;;
	*png|*jpg|*jpe|*jpeg)
		setsid feh "$url" >/dev/null 2>&1 & ;;
	*mp3|*flac|*opus|*mp3?source)
		setsid tsp wget "$url" >/dev/null 2>&1 & ;;
	*springer.com*)
		setsid curl -sO "$(curl -s "$scihub$*" | grep -Po "(?<=location.href=').+.pdf")" >/dev/null 2>&1 & ;;
	*) setsid "$TRUEBROWSER" "$url" >/dev/null 2>&1 & ;;
esac
