#!/bin/sh

# This script is called by i3 on startup.

# Increase key speed via a rate change, causing issue with i3
#xset r rate 300 50

case $HW in
    x230)
        echo "ThinkPad X230 i3 remaps"
        setxkbmap  -option ""
        #setxkbmap  -option "altwin:swap_lalt_lwin"
        setxkbmap  -option "caps:ctrl_modifier" -option "altwin:swap_lalt_lwin"
        #setxkbmap  -option "terminate:ctrl_alt_bksp" -option "caps:ctrl_modifier"
        # Map the menu button to right super as well.
        xmodmap -e 'keycode 135 = Super_R'
        # Caps pressed only once, treat it as escape.
        killall xcape ; xcape -e 'Caps_Lock=Escape'
        ;;
    mbp)
        echo "Macbook Pro i3 remaps"
        # set the Apple keyboard
        setxkbmap  -option ""
        #setxkbmap  -option "altwin:swap_lalt_lwin"
        setxkbmap  -option "caps:ctrl_modifier"
        #setxkbmap  -option "terminate:ctrl_alt_bksp" -option "caps:ctrl_modifier" -option "altwin:swap_lalt_lwin"
        # Caps pressed only once, treat it as escape.
        killall xcape ; xcape -e 'Caps_Lock=Escape'
        ;;
    x220|t520)
        echo "ThinkPad X220|T520 i3 remaps"
        setxkbmap  -option ""
        #setxkbmap  -option "altwin:swap_lalt_lwin"
        setxkbmap  -option "caps:ctrl_modifier" -option "altwin:swap_lalt_lwin"
        #setxkbmap  -option "terminate:ctrl_alt_bksp" -option "caps:ctrl_modifier"
        # Map the menu button to right super as well.
        xmodmap -e 'keycode 135 = Super_R'
        # Caps pressed only once, treat it as escape.
        killall xcape ; xcape -e 'Caps_Lock=Escape'
        ;;
    general|*)
        echo "Default i3 remaps"
        #keycode 135 = Super_R NoSymbol Super_R
        ;;
esac


#setxkbmap -rules "evdev" -model "pc105" -layout "hr,us" -option "terminate:ctrl_alt_bksp,lv3:rwin_switch,grp:shifts_toggle,caps:ctrl_modifier,altwin:swap_lalt_lwin"
