#!/bin/sh

# move workspace between primary and secondary screen
# no idea how to handle 3rd screen

screens=$(xrandr -q | grep ' connected' | cut -d " " -f 1)
# quit if having one screen
[ $(echo "$screens" | wc -l) -le 1 ] && exit 1

workspaces=$(i3-msg -t get_workspaces)
wsname=$(echo "$workspaces" | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2)
wsscreen=$(echo "$workspaces" | jq '.[] | select(.focused==true).output' | cut -d"\"" -f2)
toscreen=$(echo "$screens" | grep -v "$wsscreen" | head -1)

i3-msg -q "move workspace to output $toscreen"

